### ISSUE TITLE
#US01: Como usuario quiero poder visitar el sitio web desde diferentes dispositivos, ya sea teléfonos móviles, tablets, computadoras.

### ISSUE THREAD

**Issue by JoanaGM44** [RocketInnovate/integrador_ISP4#66]
- [x] #TK01 Realizar Componente Navbar #28
- [x] #TK02 Realizar Componente Footer #27
- [x] #TK03 Realizar maquetado del Componente Home #34 
- [x] #TK04 Realizar Componente Header #33
